Add ability to ignore certain paths
omc/searchyll pull request #44
Opened 2019-02-05 23:04 UTC by alranel

This PR introduces a configuration option that allows to ignore certain paths. Wildcards supported:

```yaml
elasticsearch:
  url: "http://localhost:9200/"     # Required. Supports auth and SSL: https://user:pass@someurl.com
                                    # Can also read URLs stored in environment variable named
                                    # BONSAI_URL and ELASTICSEARCH_URL.
  number_of_shards: 1               # Optional. Default is 1 primary shard.
  number_of_replicas: 1             # Optional. Default is 1 replica.
  index_name: "jekyll"              # Optional. Default is "jekyll".
  default_type: "post"              # Optional. Default type is "post".
  custom_settings: _es_settings.yml # Optional. No default. Relative to your src folder
  custom_mappings: _es_mappings.yml # Optional. No default. Relative to your src folder
  ignore:                           # Optional. No default.
    - /news/*
```

2020-08-16 14:46 UTC, bfabio commented
@drusellers Could you give us feedback on this one, please?

2020-10-08 13:44 UTC, drusellers requested changes
Overall looks good. A bit of error handling and we should be good to go.

2020-10-08 13:44 UTC, drusellers commented on lib/searchyll/indexer.rb
> +        #puts %(        ...ignoring)
Use `Jekyll.logger.debug`

2020-10-08 13:44 UTC, drusellers commented on lib/searchyll/indexer.rb
> +      self.ignore_regex = Regexp.new "^(#{escaped})$", Regexp::IGNORECASE
Let's put this in a `begin/rescue` with `Jekyll.logger.error` output so we can understand what the `elasticsearch_ignore` values are and the error in the process.

2020-10-28 11:22 UTC, bfabio commented
@drusellers Thanks for the review, I addressed the issues with the last commit. Let me know if you need me to squash it.

2020-10-28 12:13 UTC, drusellers approved these changes

2020-10-28 12:20 UTC, drusellers commented
> @drusellers Thanks for the review, I addressed the issues with the last commit. Let me know if you need me to squash it.

@bfabio let's get this rebase on master and I'll get it merged in. :)

2020-10-28 12:55 UTC, bfabio commented
@drusellers Done :+1:

2020-10-28 13:34 UTC, merged